project_id = "iyfwfwryibqfqetmbpqq"

[functions.analyze-report]
verify_jwt = false

[functions.check-reminders]
verify_jwt = false

[functions.validate-medical-report]
verify_jwt = false

[functions.health-chat]
verify_jwt = false